services:
  app:
    build: .
    container_name: farm-helper
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DB_HOST=private-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123321
      - DB_NAME=farm
    restart: unless-stopped
    networks:
      - farm-net

networks:
  farm-net:
    external: true
